tickers_list = [
    "ABCB4.SA",
    "ITUB4.SA",
    "TAEE4.SA",
    # "GARE11.SA",
    "BBAS3.SA",
    # "LVBI11.SA",
    "CPFE3.SA",
    # "BBSE3.SA",
    # "BRCO11.SA",
    # "BTLG11.SA",
    "CMIG4.SA",
    # "CPLE3.SA",
    # "EGIE3.SA",
    # "PMLL11.SA",
    # "RADL3.SA",
    # "FIIB11.SA",
    # "HGLG11.SA",
    # "VISC11.SA",
    "SAPR11.SA",
    "WEGE3.SA",
    "PETR4.SA",
    "VALE3.SA"
]
